# Generated by Django 2.0.7 on 2018-11-23 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SouvImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, unique=True, upload_to='order/%Y/%m/%d')),
            ],
            options={
                'ordering': ('image',),
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='orders.SouvImage'),
        ),
    ]
