# Generated by Django 2.0.7 on 2018-11-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181123_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, unique=True, upload_to='order/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='SouvImage',
        ),
    ]
